=== baapar1101/voskes.ir/.astro/collections/blog.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "slug": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "ogTitle": {
      "type": "string"
    },
    "ogDescription": {
      "type": "string"
    },
    "ogImage": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "canonical": {
      "type": "string"
    },
    "bodyHtml": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "description",
    "ogTitle",
    "ogDescription",
    "ogImage",
    "canonical",
    "bodyHtml"
  ]
}

=== baapar1101/voskes.ir/src/content/blog/creams.json
{
	"slug": "creams",
	"title": "تشویقی‌های کرمی و سالم برای گربه‌ها",
	"description": "می‌خواهید دوست چهارپایتان را با خوراکی کرمی، سالم و کم‌کالری نوازش کنید؟ این تشویقی خوشمزه برای ببر کوچک شما عالی است!",
	"ogTitle": "تشویقی‌های کرمی و سالم برای گربه‌ها",
	"ogDescription": "می‌خواهید دوست چهارپایتان را با خوراکی کرمی، سالم و کم‌کالری نوازش کنید؟ این تشویقی خوشمزه برای ببر کوچک شما عالی است!",
	"ogImage": null,
	"canonical": "https://voskes.ir/blog/creams",
	"bodyHtml": "<div class=\"d--flex\" style=\"flex-wrap: wrap;\">\n                    \n\n                                        \n                            <div id=\"id-34-77\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h1>خوراکی خامه ای و سالم!</h1>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <p>می‌خواهید دوست چهارپایتان را با خوراکی کرمی، سالم و کم‌کالری نوازش کنید؟ این تشویقی خوشمزه برای ببر کوچک شما عالی است!</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-25\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/original/creams_–_11-p.webp\" alt=\"کرم های مخصوص گربه ها\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>موجود در 3 طعم لذیذ!</h3><p>در واقع، کرم‌های ما نه‌تنها عطر و طعم می‌کنند، مصرف مایعات را افزایش می‌دهند. Prr-fection وجود دارد! بسته بندی خوش دست با درپوش چرخاننده قابل بسته شدن، همچنین به این اسنک اجازه می دهد تا دو روز پس از باز شدن در یخچال نگهداری شود.</p><img src=\"/assets/images/tip_cat.png\" class=\"float-left mr--15\" style=\"height:55px;\" alt=\"\"><p><em>آیا گربه شما اهل غذا خوردن است؟ خامه ها را به عنوان رویه روی تکه های خشک قرار دهید تا طعم بیشتری پیدا کنند. موفقیت تضمین شده است!</em></p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n                            <div id=\"id-34-89\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\">\n                    <div class=\"san-col\">\n        <div class=\"j-content txt--center pb--0 desktop-xl-pb--60\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h2>هر طعمی برای حمایت از نیازهای مختلف گربه شما با مواد اضافی غنی شده است.</h2>\n\n                </div>\n    </div>\n                </div>\n\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n                            <div id=\"id-34-88\" class=\"section section__textblock section--none section--padding bg-c--white txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h4>کرم با ماهی تن و ماهی خال مخالی</h4><p>یک خوراکی خوشمزه برای دوست چهارپای شما که عاشق ماهی است.</p><h4>خامه با مرغ</h4><p>یک میان وعده خوشمزه بدون غلات برای گربه شما که عاشق مرغ است.</p>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h4>خامه با ماهی تن و گوشت گاو</h4><p>برای کسانی که نمی توانند انتخاب کنند، ما یک نوع ماهی و گوشت داریم.</p><img src=\"/assets/images/tip_cat.png\" class=\"float-left mr--15\" style=\"height:55px;\" alt=\"\"><p>برای تعامل سرگرم کننده با گربه خود، کرم را مستقیماً از درپوش بدهید!</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-26\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--cat-primary link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-rode_kat1-images-38-26.png\" alt=\"چرا دوست پشمالو شما کرم های ما را دوست دارد\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h2>چرا دوست پشمالو شما کرم های ما را دوست دارد:</h2><ul><li><strong>کاملاً بدون دانه و گلوتن</strong></li><li><strong>مواد طبیعی</strong></li><li><strong>مصرف مایعات را ترویج می کند</strong></li><li><strong>کم کالری</strong></li><li><strong>انتخاب از 3 طعم خوشمزه 90 گرمی</strong></li><li><strong>بسته بندی با درپوش چرخاننده قابل آب بندی</strong></li><li><strong>حداقل 24 ماه و 2 روز پس از باز شدن در یخچال قابل نگهداری است</strong></li><li><strong>غنی شده با مواد اضافی برای حفظ سلامت گربه شما</strong></li></ul><img src=\"/assets/images/tip_cat.png\" class=\"float-left mr--15\" style=\"height:55px;\" alt=\"\"><p><em>بهتر است کرم ها را قبل از استفاده ورز دهید!</em></p><a href=\"/cat-treats/creams.html\" class=\"btn mt--15 btn--nero btn--normal\">تمام طعم ها را کشف کنید</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n            </div>"
}

=== baapar1101/voskes.ir/src/content/blog/soft-chewy-snacks.json
{
	"slug": "soft-chewy-snacks",
	"title": "Discover our small soft cat treats",
	"description": "Voskes' small, soft chewy treats are healthy and suitable for both growing kittens and adult cats and make a delicious treat between meals or the purrrr-fect reward to teach your cat a host of tricks.",
	"ogTitle": "Discover our small soft cat treats",
	"ogDescription": "Voskes' small, soft chewy treats are healthy and suitable for both growing kittens and adult cats and make a delicious treat between meals or the purrrr-fect reward to teach your cat a host of tricks.",
	"ogImage": null,
	"canonical": "https://voskes.nl/en/blog/soft-chewy-snacks",
	"bodyHtml": "<div class=\"d--flex\" style=\"flex-wrap: wrap;\">\n                    \n\n                                        \n                            <div id=\"id-34-71\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h1>SOFT CHEWS AS PURRR-FECT TREATS!</h1>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <p>Voskes' small, soft chewy treats are healthy and suitable for both growing kittens and adult cats and make a delicious treat between meals or the <em>purrrr-fect</em> reward to teach your cat a host of tricks.</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                                \n  \n<div id=\"id-38-27\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--2by1 ar--2by1 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-snoepjes_18-images-38-27.png\" alt=\"FOR BOTH FISH AND MEAT LOVERS\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>FOR BOTH FISH AND MEAT LOVERS</h3><p>With our different variants with chicken, duck or fish, there is guaranteed to be a cat snack for both four-legged fish fanatics and purebred meat lovers!</p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                                \n  \n<div id=\"id-38-30\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--2by1 ar--2by1 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-snoepjes_11-images-38-30.png\" alt=\"AT VOSKES, QUALITY IS KEY\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>AT VOSKES, QUALITY IS KEY</h3><p>Besides outstanding taste, the ingredients and nutritional values of your cat's favourite snack are something to consider. At Voskes, excellent ingredients are key, so with Voskes snacks, your housemate will always enjoy a delicious cat snack without any worries!</p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                                \n  \n<div id=\"id-38-29\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--2by1 ar--2by1 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-snoepjes_152-images-38-29.png\" alt=\"Snacks for kittens\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>FOR KITTENS TOO!</h3><p>Even the littlest ones love to be pampered sometimes! That's why our Voskes cat treats are also suitable for kittens from 3 months onwards.<br>Take care though, kittens still have a lot to grow and develop, so in the first year it is important they get the right nutrients. These get the best out of <strong><a href=\"/en/products/kitten-complete-chicken.html\" title=\"full-fat kitten food.\">full-fat kitten food.</a></strong></p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-28\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--cat-primary link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-stapelen1-images-38-28.jpg\" alt=\"SOFT &amp; CHEWY TREATS for your cat\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>WHY OUR SOFT &amp; CHEWY TREATS ARE IDEAL REWARDS FOR YOUR PET TIGER:</h3><ul><li><strong>Easy to chew</strong></li><li><strong>Suitable for kittens from 3 months</strong></li><li><strong>Easily digestible</strong></li><li><strong>Contain a lot of animal proteins</strong></li><li><strong>For both fish and meat lovers</strong></li><li><strong>Low in fat</strong></li><li><strong>A delicious taste!</strong></li></ul><a href=\"/en/cat-treats/soft-chewy-snacks.html\" class=\"btn mt--15 btn--nero btn--normal\">همه طعم‌ها را ببینید</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n            </div>"
}

=== baapar1101/voskes.ir/src/content/blog/drinks.json
{
	"slug": "drinks",
	"title": "Delicious cat drinks with fine pieces of meat and fish",
	"description": "These delicious broths are ideal for furry friends who do not absorb enough moisture. Discover the catproducts of Voskes.",
	"ogTitle": "Delicious cat drinks with fine pieces of meat and fish",
	"ogDescription": "These delicious broths are ideal for furry friends who do not absorb enough moisture. Discover the catproducts of Voskes.",
	"ogImage": null,
	"canonical": "https://voskes.nl/en/blog/drinks",
	"bodyHtml": "<div class=\"d--flex\" style=\"flex-wrap: wrap;\">\n                    \n\n                                        \n                            <div id=\"id-34-79\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h1>HMMM...CAT SOUPS<br>WITH FINE PIECES OF<br>MEAT AND FISH</h1>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <p><strong>Voskes' coveted cat soups? These are really ideal for furry friends who don't drink enough.</strong> This is because cats on a menu of mainly dry food are particularly prone to urolith formation (bladder stones), as they do not absorb enough fluids. For that reason, our tasty drinks encourage your cat to drink more, thanks to the delicious taste of broth with fine pieces of fish and meat.</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-31\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-zonder_toegevoegd_zout1-images-38-31.png\" alt=\"HYDRATION... A MUST for cats\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>HYDRATION... A MUST!</h3><p>Cats generally don’t drink much. In the wild, they get a lot of moisture through their prey animals, which consist of 65-75% water. The other thing is, your cat's tongue is not designed to drink a lot of water in one go. With its rough barbs, it actually makes it quite tricky for your four-footed friend.</p><p>Your cat will therefore need to be enticed to drink: a running water tap, an inviting puddle of rainwater, a deliciously flavoured drink... To provide your cat with sufficient fluids, not only wet food, but also our Soups are ideal in your little tiger's menu.</p><p>This is because if a cat doesn’t drink enough, it negatively affects the urinary tract, with an increased risk of bladder stones. So definitely encourage your furry friend to drink enough !</p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-22\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/original/drinks_eng1-p.webp\" alt=\"Soupflavours of Voskes for your cat\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>EACH FLAVOUR IS ENRICHED WITH EXTRAS TO SUPPORT YOUR CAT'S DIFFERENT NEEDS</h3><ul><li><strong>Soup with tuna:</strong> healthy digestion through prebiotics</li><li><strong>Soup with salmon:</strong> supports healthy bones and joints</li><li><strong>Soup with chicken:</strong> promotes healthy intestinal flora</li><li><strong>Soup with beef:</strong> supports the immune system</li></ul><h3>TIP!</h3><p>You can place this cat soup in a drinking bowl next to food or pour it over dry kibble as a topping for extra flavour!</p><a href=\"/en/cat-treats/drinks.html\" class=\"btn mt--15 btn--nero btn--normal\">مشاهده محصولات</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-23\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--cat-primary link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-kat_op_tak1-images-38-23.png\" alt=\"Benefits of our soups for cats\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h2>GOOD REASONS TO CHOOSE OUR DRINKS:</h2><ul><li><strong>Stimulates hydration</strong></li><li><strong>With delicious, fine pieces of fish or meat</strong></li><li><strong>Grain-, gluten- and soy-free</strong></li><li><strong>Without added salt</strong></li><li><strong>4 delicious flavours</strong></li><li><strong>Easy-to-open 50gr cans</strong></li><li><strong>Can be kept for at least 36 months and 2 days after opening in the fridge</strong></li></ul></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n            </div>"
}
