=== baapar1101/voskes.ir/.astro/collections/blog.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "slug": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "ogTitle": {
      "type": "string"
    },
    "ogDescription": {
      "type": "string"
    },
    "ogImage": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "canonical": {
      "type": "string"
    },
    "bodyHtml": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "description",
    "ogTitle",
    "ogDescription",
    "ogImage",
    "canonical",
    "bodyHtml"
  ]
}

=== baapar1101/voskes.ir/src/content/blog/jelly-cups.json
{
	"slug": "jelly-cups",
	"title": "Velvety tuna-based treats of Voskes",
	"description": "With these cups filled with jelly and fine pieces of fish or meat, you will be able to tempt even the pickiest cat. They are irresistibly delicious!",
	"ogTitle": "Velvety tuna-based treats of Voskes",
	"ogDescription": "With these cups filled with jelly and fine pieces of fish or meat, you will be able to tempt even the pickiest cat. They are irresistibly delicious!",
	"ogImage": null,
	"canonical": "https://voskes.nl/en/blog/jelly-cups",
	"bodyHtml": "<div class=\"d--flex\" style=\"flex-wrap: wrap;\">\n                    \n\n                                        \n                            <div id=\"id-34-78\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h1>A GOURMET DELICACY!</h1>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <p>With these cups filled with jelly and fine pieces of fish or meat, you will be able to tempt even the pickiest cat. They are irresistibly delicious!</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-20\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--nero link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-jelly_snack1-images-38-20.png\" alt=\"THESE VELVETY JELLIES COME IN 5 DIFFERENT FLAVOURS\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>THESE VELVETY JELLIES COME IN 5 DIFFERENT FLAVOURS</h3><p>Hand-picked, choicest pieces of fish in a soft jelly. These delicious flavours from the sea are a true delicacy for even the choosiest cat! Looking for the ideal, grain-free treat for your little tiger? One box contains 6 convenient, ready-to-use 25g portion packs, so... what are you waiting for! It's meow or never!</p></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-21\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--cat-primary link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-jelly_verpakking_–_21-images-38-21.png\" alt=\"BENEFITS OF OUR DELICIOUS JELLY CUPS\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h2>BENEFITS OF OUR DELICIOUS JELLY CUPS</h2><ul><li><strong>5 premium tuna-based flavours</strong></li><li><strong>6 easy-to-open portion packs</strong></li><li><strong>High proportion of omega 3 &amp; omega 6 fatty acids</strong></li><li><strong>Rich in vitamin E</strong></li><li><strong>Rich in taurine</strong></li><li><strong>Grain- and gluten-free</strong></li></ul><a href=\"/en/cat-treats/jelly-cups.html\" class=\"btn mt--15 btn--nero btn--normal\">همه طعم‌ها را ببینید</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n            </div>"
}

=== baapar1101/voskes.ir/src/content/blog/complementary-wet-food.json
{
	"slug": "complementary-wet-food",
	"title": "Tasty jelly cat snacks of Voskes",
	"description": "Is your cat a true carnivore? Then he can't believe his luck! Voskes tins with soft jelly or paté full of delicious, tender pieces of fish or meat are a real treat for any cat.",
	"ogTitle": "Tasty jelly cat snacks of Voskes",
	"ogDescription": "Is your cat a true carnivore? Then he can't believe his luck! Voskes tins with soft jelly or paté full of delicious, tender pieces of fish or meat are a real treat for any cat.",
	"ogImage": null,
	"canonical": "https://voskes.nl/en/blog/complementary-wet-food",
	"bodyHtml": "<div class=\"d--flex\" style=\"flex-wrap: wrap;\">\n                    \n\n                                        \n                            <div id=\"id-34-72\" class=\"section section__textblock section--none section--padding bg-c--hard-conversion txt-c--nero title-c--nero link-c--nero\">\n      <div class=\"san-container\" data-span=\"full-desktop\">\n                    <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n        <div class=\"j-content txt--left pb--0 desktop-xl-pb--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <h1>IRRESISTIBLY DELICIOUS PIECES OF FISH OR MEAT IN JELLY OR PATE!</h1>\n\n                </div>\n    </div>\n    </div>\n\n  <div class=\"san-col\" data-span=\"12 desktop-xl-6\">\n          <div class=\"j-content txt--left pt--0 desktop-xl-pt--60\" data-block=\"\" data-type=\"container\">\n      <div class=\"j-content\" data-type=\"text\">\n          <p>Is your cat a true carnivore? Then he can't believe his luck! Voskes tins with soft jelly or paté full of delicious, tender pieces of fish or meat are a real treat for any cat.</p>\n\n                </div>\n    </div>\n        </div>\n          </div>\n</div>\n            \n            \n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-32\" class=\"highlight section section--none txt-c--nero bg-c--white title-c--chicken link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-blikjes_gelei_stapel1-images-38-32.png\" alt=\"jelly or paté for cats\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h3>CHOOSE FROM 22 SURPRISING FLAVOUR SENSATIONS!</h3><p>This jelly or paté contains <strong>only natural ingredients</strong>. The fish and meat are carefully <strong>steamed</strong> to preserve all nutrients and aromas even better. Moreover, the fish comes from <strong>sustainable fishing</strong>. There is a choice of <strong>22 unique recipes</strong> based on fish or meat so you have plenty of choice to spoil your furry housemate. What's not to like?</p><h3>HEALTHY SKIN &amp; COAT</h3><p>Our <strong>85 g jelly cans</strong> are rich in <strong>animal proteins and fatty acids</strong>, contributing to <strong>shiny, healthy skin and coat</strong>. They make a great addition to the menu of your four-legged furry friend and- are ideal for fully indulging your cat. In the morning when you get up or in the evening when you come home: our tins of jelly are the absolute highlight of your house tigers' day, so... Enjoy your taste of happiness!</p><a href=\"/en/cat-food/complementary-wet-food.html\" class=\"btn mt--15 btn--nero btn--normal\">همه طعم‌ها را ببینید</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n                    \n\n                                        \n            \n            \n                              \n\n<div id=\"id-38-33\" class=\"highlight section section--none txt-c--nero bg-c--transparent title-c--cat-primary link-c--nero link-hc--nero\">\n    <div class=\"san-container p--0\" data-span=\"full\" data-options=\"\" data-no-gap=\"\"><div class=\"san-col highlight__media highlight__media--half\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-2\"><div class=\"ar-tablet-lg--4by3 ar--4by3 ar\" style=\"height: 100%;\"><div class=\"highlight__single-image ar__content\">\n      <img src=\"/uploads/landscape/landscape-landscape-cat_visual_blogpost_2-images-8-58-images-38-33.png\" alt=\"WHY YOUR CAT IS A FAN OF OUR JELLY AND PATÉ CANS\" loading=\"lazy\" decoding=\"async\" class=\"obj--cover\">\n</div>\n</div></div><div class=\"san-col pv--15 tablet-lg-pv--0\" data-span=\"12 tablet-lg-6\" data-order=\"tablet-lg-1\" data-options=\"extra-padding--tablet-lg\"><div class=\"san-container ps--0 mobile-lg-ps--15 tablet-lg-ps--0 h-100\" data-span=\"full-tablet-lg\"><div class=\"san-col tablet-lg-ps--0\"><div class=\"j-content\" data-type=\"container\" data-centered=\"\" data-block=\"\"><div class=\"j-content txt--left\" data-type=\"text\"><h2>REASONS WHY YOUR CAT IS A FAN OF OUR JELLY AND PATÉ CANS:</h2><ul><li><strong>22 exclusive recipes based on fish or meat, something for everyone</strong></li><li><strong>Irresistibly tastyyyyyy</strong></li><li><strong>Cans of 85 g with only natural ingredients</strong></li><li><strong>Steamed and prepared by hand</strong></li><li><strong>Easily digestible</strong></li><li><strong>Ocean-friendly; no fish from overfished areas, no drift nets</strong></li><li><strong>High proportion of essential amino acids</strong></li><li><strong>Rich in animal proteins</strong></li></ul><a href=\"/en/cat-food/complementary-wet-food.html\" class=\"btn mt--15 btn--nero btn--normal\">همه طعم‌ها را ببینید</a></div></div>\n</div></div></div></div>\n</div>\n            \n            \n            \n            \n            \n            \n            </div>"
}
